### ISSUE TITLE
Not all Spotify albums have >1 image

### ISSUE THREAD

**Issue by hughrawlinson** [jch254/audio-insights#1]
Hi,

This project looks awesome, and I can't wait to try it out, but, it's currently not working properly for me. I think the problem stems from the Spotify API returning an album that doesn't have more than one image: `t.album.images[1] is undefined`. In fact, some Spotify Albums may not have any image at all, so it might be a good idea to try/catch this whole statement with the catch returning the URL to an empty album cover image.

Looking forward to seeing this project working!

Best,

Hugh

**Comment by jch254** [comment]
Hey @hughrawlinson!

Thanks so much for checking out the project. That makes absolute sense, I must've been lucky to have a set of albums with multiple images. This is fantastic as images[0] seem to be higher definition which makes the mosaic look glorious! However I'm thinking to check for images[1] before images[0] as it seems to be a smaller file size and improves the loading speed of the mosaic. 

I've made some changes in the following commit which should fix the issue: https://github.com/jch254/audio-insights/commit/5c54ed05b16fe9af9001ca1a57c75685eeba81e3. I've also pushed these changes to the live demo which should appear once CloudFront invalidates 👍
